travis:
  secure:
    BINSTAR_TOKEN: Pe58ShMeuBO/NXKVJkE6NG3lvHFljFsYMO2+RIbCa/2ofE/9fJOXMkDeDxGc4MgSaYAPoEaoiMoIBucTwYDqdFbEC0uqQBesgHlwLXhZFjn1rHWO5saszNZnr8Ax2r0ggy5EVkm3gyjZEZ36QhHOxsXyD3DU2/dQzidUW31YtwC8pQ4Cl/hUXTRhnbAOfzKSghm+7Gv75PlvinHghnCn1fin/A19qU7CvD0T+M+rNJdFThTkwd9HURCe2kMSFDnZBWRB6TdZdsbJO4YmaCn+8EjYbbe3boz9FF22SQ8j+faQu7jvt+NYSJsCo0GIJ0YXkWMK+gSple0NV6CZiVb/U226XzJllCiJewb5nPQPnX05xUAu7LD6LWQ/XUQ7+6f8FOrmIa9nN5tup34y58mpxKd7R/4l3AHihjRbbW7iz/5rPi/AgjiHISXOE3kDDO7XpgeJ7c78rDiYym8bSAsDHR6pT8GDcR/JoY3eoJ07ADMTkhWOhgSiI68TLd9JtcoSYQjXRb6kXjAcWChHmzzKYsiGrkDpuS9jtVBrFq33Zzu/gic6BGLFScHbasaVMMLn28DBSKoxFAwYvEkiYPd/vlRnTYd6lZAwsLFYmAnySClqUVweHFcc9PZNECS0WsrAhJLWezohvu2lkSc87XDmGkpX2rL7RcardxMKXQY3+vA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
